apiVersion: apps/v1
kind: Deployment
metadata:
  name: mask-detector-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mask-detector-app
  template:
    metadata:
      labels:
        app: mask-detector-app
    spec:
      containers:
      - name: mask-detector-app
        image: gcr.io/new-new-419022/mask-detector-app:v2
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: mask-detector-app
spec:
  selector:
    app: mask-detector-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
  type: LoadBalancer
