name: Continuous Integration/Training/Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Create auth_bucket.json
        run: |
          echo '${{ secrets.GCP_BUCKET }}' > auth_bucket.json

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: pytest

      - name: Train model
        run: python train.py

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: new-new-419022
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Install gke-gcloud-auth-plugin
        run: gcloud components install gke-gcloud-auth-plugin

      - name: Authenticate Docker with GCR
        run: gcloud auth configure-docker gcr.io

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/new-new-419022/mask-detector-app:1.0.4 .
          docker push gcr.io/new-new-419022/mask-detector-app:1.0.4

      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials mask-detector-cluster --zone europe-west1-b --project new-new-419022
          kubectl apply -f kubernetes/deployment.yaml

      - name: Verify deployment
        run: kubectl get all